### ISSUE TITLE
Outline view nesting issue

### ISSUE THREAD

**Issue by damieng** [facebook-atom/atom-ide-ui#176]
![image](https://user-images.githubusercontent.com/118951/36820075-fdaa7e14-1ca0-11e8-9cc8-b8bf8837b214.png)

filterChangeWatchedFiles should be shown below TypeScriptLanguageClient not onDidConvertAutocomplete - the result payload looks like this;

![image](https://user-images.githubusercontent.com/118951/36820154-5e320a90-1ca1-11e8-92b0-9916401df7d4.png)

This occurs in both 0.9.1 and 0.9.2 (and possibly earlier)

**Comment by laughedelic** [comment]
I can confirm that this occurred earlier. Can't say exactly, but for sure _before_ 0.9.0.

**Comment by laughedelic** [comment]
In fact, I found a screenshot dated by **February 7**, that I was going to use to report this (but then forgot 😅). So I think it was introduced in **v0.8.0**.

<img width="980" alt="screen shot 2018-02-07 at 18 42 00" src="https://user-images.githubusercontent.com/766656/36855972-25e8fc14-1d75-11e8-8799-676034297842.png">

**Comment by damieng** [comment]
Hey @wbinnssmith any thoughts on this?  It looks like the ol/li isn't nested in the dom so not sure what the intent was on how to identify the nesting here. Basically direct items beneath a branch have the same nesting as children below a peer.  (getGrammarScopes, getLanguageName, getServerName and filterChangedWatchedFiles in my screenshot should all be considered the same 'level' as startServerProcess - not its children)

**Comment by matthewwithanm** [comment]
thanks for the report! looks like this is a simple repro:

```py
class P:
    p = 1
    class K:
        k = 1
```

**Comment by wbinnssmith** [comment]
thanks @laughedelic @damieng @matthewwithanm !

going to look into this soon.

**Comment by laughedelic** [comment]
Here's another screenshot, which shows that the problem could be about rendering the list, not the nesting itself (that's why I opened #192 before):

<img width="832" alt="screen_shot_2018-04-08_at_00_07_46" src="https://user-images.githubusercontent.com/766656/38460876-3a279f6c-3ac3-11e8-97f2-9377416bbdcd.png">

In this outline the only misplaced items are highlighted, the red line shows that they are on the same level as `autoImport` in the code. And `autoImport` is placed correctly in the tree (with right indentation).

Notice also that the rest of the outline is correct: the `Metals` node has many children and they are all placed correctly.

**Comment by laughedelic** [comment]
Here is a better demo:

![2018-04-08 00 32 21](https://user-images.githubusercontent.com/766656/38460921-5b4d6612-3ac4-11e8-872d-532f4203574c.gif)

You see that `x` and `y` are aligned correctly, but appearance of the second level of nesting (`foo.x.y`) changes alignment of all other children.

**Comment by matthewwithanm** [comment]
this should be better in next week's release. thanks @peterhal for the fix!

**Comment by hansonw** [comment]
Will publish a release with https://github.com/facebook-atom/atom-ide-ui/commit/7a73f338342784cf4890363fcfb7209c08417c78 soon :)
