### ISSUE TITLE
PHP debug?

### ISSUE THREAD

**Issue by tiagonervis** [facebook-atom/atom-ide-ui#212]
Hello, is there any possibility for debug module development for php?

**Comment by PHLAK** [comment]
I too would like an official atom-ide-debugger-php package for debugging with Xdebug. This would be an incredibly valuable package for myself (and others I'm sure) and help differentiate Atom from Sublime Text by bringing it one step closer to a true IDE like PhpStorm.

**Comment by ebluestein** [comment]
XDebug is no longer supported in Nuclide. We now only support debugging hack on HHVM (version 3.24 or later).

**Comment by PHLAK** [comment]
@ebluestein Pardon my ignorance but what does Nuclide support have to do with getting a atom-ide-debugger-php package working? Also, why not support Xdebugger? I would venture a guess that many, if not most, PHP developers aren't or can't run HHVM.

**Comment by ebluestein** [comment]
Hey @PHLAK , 

This package (atom-ide-ui and friends) are provided and maintained by the Nuclide team at Facebook. 

We've never explicitly supported using the Nuclide Hack/PHP debugger on servers other than HHVM, but since Nuclide spoke to HHVM using the XDebug protocol, it's possible that it could be used with other PHP implementations even though it wasn't officially supported.

We removed the Nuclide XDebug debugger several releases ago, and actually completely removed XDebug from HHVM as well. Our old implementation (both the Nuclide debugger portion, as well as the debugging engine on the HHVM side) was riddled with known issues making it extremely unreliable, and the XDebug protocol did not give us the flexibility we need to move quickly and iterate on features moving forward.

Additionally, all debuggers supported by Nuclide (including the atom-ide-* packages provided by our team) have migrated to the Visual Studio Code Debug Adapter Protocol. This open source protocol maintained by the VS Code team at Microsoft allows us to, among other things, unify all our debuggers behind the same protocol and allow the UX to speak a single language. 

Unfortunately our existing XDebug infrastructure could not come along with us.

This of course doesn't in any way prevent a third party package from providing support for PHP/XDebug, but going forward our team will only be providing support for Hack on HHVM.
