### ISSUE TITLE
multi line select keyboard shortcut gets overridden to wrong key combination in windows

### ISSUE THREAD

**Issue by JoueBien** [facebook-atom/atom-ide-ui#240]
### Description
While using windows the hyper click setting for "trigger key" for windows is ignored and uses the OSX command key (windows key/command key) while using windows. This causes the multiline select shortcuts ctrl+click to be changed to windows key+click

### Expected Behavior
multiline select keyboard shortcut should be  should ctrl+click

### Actual Behavior
multiline select keyboard shortcut gets overridden to windows key+click

### Versions
* Atom: 1.26.1
* Client OS: windows running on a macbook pro
* atom-ide-ui: v0.11.2 & v0.11.1

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by hansonw** [comment]
We've found this to be a sensible default for users who come from other IDEs (since ctrl+click is mapped to go-to-definition in many other tools.) But it's easy to override this - it's a setting in the "Hyperclick" section:

<img width="440" alt="screen shot 2018-07-17 at 9 40 15 pm" src="https://user-images.githubusercontent.com/577378/42859976-042528bc-8a0a-11e8-87a3-94af8af10f4c.png">

**Comment by JoueBien** [comment]
yeah? because bring up the start menu is such a great thing when you want to select multiple lines in windows. 
Recommend reopening issue because hansonw  you clearly missed what the actual issue is. 
It's a bug where when in windows the key combination doesn't match the settings.

**Comment by hansonw** [comment]
Hyperclick only replaces the ctrl+click multiline selection if it's set to
use ctrl+click in the settings. Try setting it to winkey+click instead and
you should have your multiline select shortcut back.
