### ISSUE TITLE
I have lost multi cursors

### ISSUE THREAD

**Issue by DavidTorrijos** [facebook-atom/atom-ide-ui#299]
Hi there!
Before I install atom-ide-ui package, I could create multiple cursors at different lines using:
**_cmd + click_** at the line which I wanted to write.

I have lost this functionality after install it and I don't see in the package settings where I can retrieve it.
If I disable the package, the multi cursors shortcut works properly.
Thanks!

**Comment by evangrayk** [comment]
I believe this is because we use cmd-click for hyperclick / go-to-definition. I think multiple cursors is bound to cmd-shift-click because of this. Under atom-ide-ui settings  you can change the hyperclick trigger, atom-ide-ui Settings > Hyperclick > Trigger Keys for macOS, which should remove the conflict!

**Comment by DavidTorrijos** [comment]
You're right, I close the issue.
Thank you so much and congrats for the package ❤️
