### ISSUE TITLE
Provide way to theme terminal

### ISSUE THREAD

**Issue by ryanolsonx** [facebook-atom/atom-ide-ui#308]
Currently, you can customize the terminal colors using the configuration in settings. Ideally, there would be a way to customize the terminal theme based on the theme you select.  Is there a way to improve this so that I can setup my own solarized colors for terminal and then if I switch to atom one dark, switch to those colors?

**Comment by pelmers** [comment]
Hi, this isn't a built-in feature now, but you could easily script the behavior in an init script as a custom Atom command or similar.

The settings there are just Atom config, listed at https://github.com/facebook/nuclide/blob/master/modules/atom-ide-ui/pkg/atom-ide-terminal/package.json#L140-L236.

To change the settings you can use:
```
atom.config.set('nuclide.atom-ide-terminal.black', '#<RRGGBB>');
atom.config.set('nuclide.atom-ide-terminal.red', '#<RRGGBB>');
...
```

If you're interested in contributing a pull request, please feel free to tag me for review! But otherwise we probably will not make adding this feature to the settings UI a priority.

**Comment by ryanolsonx** [comment]
Thanks! I think that'll be fine for now. It doesn't seem like you can provide theming capabilities using a less css file (since this isn't themed like the rest of atom).
