### ISSUE TITLE
Embedded diff viewer - suggestion

### ISSUE THREAD

**Issue by niccolomineo** [facebook-atom/atom-ide-ui#42]
Hi, this is just a suggestion: what about a diff viewer, like IntelliJ Idea?

**Comment by hansonw** [comment]
Nuclide used to have a diff viewer as well, but we're trying not to be the kitchen sink with atom-ide-ui, especially since this functionality exists in other places.

Have you tried `split-diff`? https://atom.io/packages/split-diff
Atom's new GitHub functionality also allows you to view 'git diff' output in the UI now if you want multi-file diffs.
