### ISSUE TITLE
Expose a way to enable/disable specific diagnostics

### ISSUE THREAD

**Issue by wldcordeiro** [facebook-atom/atom-ide-ui#49]
### Description
If you use both the Flow and Typescript IDE tools you'll have lots of errors in Flow codebases coming from the Typescript IDE diagnostics. I'd like a way to be able to pref off/on the diagnostics so that I can use the two in concert as I work in both types of codebases.

### Versions
* Atom: 1.21.beta1
* Client OS: OS X
* atom-ide-ui: 0.3.3

**Comment by hansonw** [comment]
I believe this will be part of the improvements coming in #39 (although correct me if I'm wrong, @matthewwithanm). You can follow the thread over there.

**Comment by wldcordeiro** [comment]
@hansonw that issue seems concerned with the panel in particular?

**Comment by hansonw** [comment]
The panel may have a 'sources' box at some point in the future where you can disable/enable specific providers.

**Comment by matthewwithanm** [comment]
@hansonw No, nothing planned for this…

It seems like you'd want to disable the package whose diagnostics you don't want, no? Otherwise one of them is doing unnecessary work.

**Comment by Arcanemagus** [comment]
> It seems like you'd want to disable the package whose diagnostics you don't want, no?

Enabling/disabling a package is a bit heavy handed when you frequently switch between projects that use both. Granted they should be expanded to provide an option to only work when they have a configuration available, but that shouldn't be relied on.

**Comment by matthewwithanm** [comment]
I dunno. Barring the ability to enable packages on a per-project basis, I think it really is up to the packages. Hiding the messages is really just working around the symptom imo. Maybe this can act as a forcing function for those package authors to quit early when there's no config. I'd hate for us to mask the problem with filters and then people to think that Atom IDE is slow just because they have five diagnostic providers doing work—the results of which we're hiding.

**Comment by Arcanemagus** [comment]
> Hiding the messages is really just working around the symptom imo

FYI, the `linter` command that does this doesn't hide the messages, it disables calling `lint()` on disabled providers. Making the provider do all the work only to ignore the results is a bit silly.

**Comment by matthewwithanm** [comment]
Yeah, but that's only pull-based linters right?

> Making the provider do all the work only to ignore the results is a bit silly.

Glad we're agreed 😊

**Comment by Arcanemagus** [comment]
> Yeah, but that's only pull-based linters right?

Hmmm, an excellent question. From what I can tell you're right that only pull-based linters work that way. Push-based linters control when they trigger on their own so it has no control over them... which is the exact situation with the `ide-*` providers.

Without an API change I'm not sure there is a way to handle this for push-based linters other than ignoring their messages as you initially said 😕. Those individual `ide-*` providers should definitely be implementing a "disable when no config" option though, it's always one of the most requested things with linters that have a configuration.

**Comment by LeaVerou** [comment]
This would be great, why is this issue closed since nothing was planned?

> It seems like you'd want to disable the package whose diagnostics you don't want, no? Otherwise one of them is doing unnecessary work.

Some packages are buggy with their diagnostics, but still useful for other things, e.g. outline view (ide-css being one example). Disabling the package altogether is throwing the baby out with the bathwater, but buggy linting is *extremely* disconcerting.
